//!javascript
/*
 * AUTOGENERATED - DO NOT EDIT THIS FILE, USE dwbem -E <extension> INSTEAD!
 */

//<adblock_subscriptions___SCRIPT
extensions.load("adblock_subscriptions", {
//<adblock_subscriptions___CONFIG

// Shortcut to subscribe to a filterlist
scSubscribe : null, 
// Command to subscribe to a filterlist
cmdSubscribe : "adblock_subscribe", 

// Shortcut to unsubscribe from a filterlist
scUnsubscribe : null, 

// Command to unsubscribe from a filterlist
cmdUnsubscribe : "adblock_unsubscribe",

// Shortcut to update subscriptions and reload filter rules
// Note that dwb will also update all subscriptions on startup
scUpdate : null, 

// Command to update subscriptions and reload filter rules
// Note that dwb will also update all subscriptions on startup
cmdUpdate : "adblock_update", 

// Path to the filterlist directory, will be created if it doesn't exist. 
filterListDir : data.configDir + "/adblock_lists"
//>adblock_subscriptions___CONFIG
});
//>adblock_subscriptions___SCRIPT
//<requestpolicy___SCRIPT
extensions.load("requestpolicy", {
//<requestpolicy___CONFIG
// path to a whitelist 
whiteList : data.configDir + "/" + data.profile + "/requestpolicy.json",

// shortcut to block/allow requests
shortcut : "aze",

// shortcut to unblock requests from current site that are blocked on all
// sites
unblockCurrent : "erC",

// shortcut to unblock requests that are blocked on all sites
unblockAll : "erA",

// reload current site after blocking / unblocking a request
autoreload : false, 

// notify about blocked requests
notify : false

//>requestpolicy___CONFIG
});
//>requestpolicy___SCRIPT
//<userscripts___SCRIPT
extensions.load("userscripts", {
//<userscripts___CONFIG
  // paths to userscripts, this extension will also load all scripts in 
  // $XDG_CONFIG_HOME/dwb/greasemonkey, it will also load all scripts in
  // $XDG_CONFIG_HOME/dwb/scripts but this is deprecated and will be
  // disabled in future versions.
  scripts : []
//>userscripts___CONFIG
});
//>userscripts___SCRIPT
//<contenthandler___SCRIPT
/*<contenthandler___DISABLED
extensions.load("contenthandler", {
//<contenthandler___CONFIG
  // The handler can either be a string or a function, if it is a string
  // %u will be replaced with the uri of the request, if the handler is a
  // function the first parameter of the function will be the uri and the
  // function must return the command to execute.
  
  // Handle requests based on filename extension
  extension : {
    // "torrent" : "xterm -e 'aria2 %u'", 
   //"pdf" : "xterm -e 'm=`basename %u` ; wget %u -O /tmp/$m ; evince /tmp/$m'"
  },

  // Handle requests based on URI scheme
  uriScheme : {
      //ftp : function(uri) { 
      //    if (uri[uri.length-1] == "/") 
      //        return "xterm -e 'ncftp " + uri + "'"; 
      //    else 
      //        return "xterm -e 'ncftpget " + uri + "'"; 
      //}
  },

  // Handle requests based on MIME type
  mimeType : {
  //  "application/pdf" : "xterm -e 'm=`basename %u` ; wget %u -O /tmp/$m ; evince /tmp/%m'"
  }
//>contenthandler___CONFIG

});
contenthandler___DISABLED>*/
//>contenthandler___SCRIPT

//<cookies___SCRIPT
extensions.load("cookies");
//>cookies___SCRIPT
